---
blueprint:
  name: Gaggiuino Heated Up Notification
  description: Notify when Gaggiuino is heated up
  domain: automation
  input:
    connectivity:
      name: Gaggiuino Connectivity Binary Sensor
      description: The binary sensor that indicates if Gaggiuino is connected.
      default: binary_sensor.gaggiuino_availability
      selector:
        entity:
          filter:
            - domain: binary_sensor
              integration: gaggiuino
              device_class: connectivity

    target_temperature:
      name: Gaggiuino Target Temperature Sensor
      description: The sensor for the Gaggiuino Target Temperarure
      default: sensor.gaggiuino_target_temperature
      selector:
        entity:
          filter:
            - domain: sensor
              integration: gaggiuino
              device_class: temperature

    temperature:
      name: Gaggiuino Current Temperature Sensor
      description: The sensor for the Gaggiuino Current Temperarure
      default: sensor.gaggiuino_temperature
      selector:
        entity:
          filter:
            - domain: sensor
              integration: gaggiuino
              device_class: temperature

    profile_name:
      name: Gaggiuino Profile Name Sensor
      description: The entity for the Gaggiuino Profile Name Sensor
      default: sensor.gaggiuino_profile_name
      selector:
        entity:
          filter:
            - domain: sensor
              integration: gaggiuino

    off_profile_name:
      name: Gaggiuino OFF Profile Name
      description: "Gaggiuino 'OFF' Profile Name."
      default: "OFF"
      selector:
        text:

    notify_device:
      name: Device to notify
      description: Device to send notification to
      selector:
        device:
          integration: mobile_app


mode: single


variables:
  target_temperature_entity_id: !input target_temperature
  temperature_entity_id: !input temperature


trigger_variables:
  target_temperature_entity_id: !input target_temperature
  temperature_entity_id: !input temperature


triggers:
  - trigger: template
    value_template: >-
      {{
      (
        states(target_temperature_entity_id) - states(temperature_entity_id)
      ) >= 0
      }}


conditions:
  - and:
      - condition: state
        entity_id: !input connectivity
        state: "on"

      - condition: template
        value_template: >-
          {{ now() > state_attr(this.entity_id,'last_triggered') + timedelta(hours=1) }}

      - not:
          - condition: state
            entity_id: !input profile_name
            state: !input off_profile_name

actions:
  - action: system_log.write
    data:
      message: "Gaggiuino heated up to {{ states(temperature_entity_id) }}"
      level: info

  - device_id: !input notify_device
    domain: mobile_app
    type: notify
    message: "Gaggiuino heated up to {{ states(temperature_entity_id) }}"
